### ISSUE TITLE
Fine-tuned model

### ISSUE THREAD

**Issue by SofiaLugli** [vasr-dataset/vasr#6]
Hi there, 
I'm really interested in your work. I would like to ask you if the model fine-tuned on the VASR dataset is available somewhere. As I am working on a similar task, I think it would be interesting to see its performance on my dataset as well. 
Thank you :)

**Comment by yonatanbitton** [comment]
Hi, thanks for the interest!
We didn't save the model, but it can be re-trained using the instructions in https://github.com/vasr-dataset/vasr/tree/main/experiments#trainable
Also, now there are newer models, so welcome to add it to your model's training mixture if it will help :)

**Comment by SofiaLugli** [comment]
Thank you, I'll do that then.
Cheers :)
