### ISSUE TITLE
Unable to download vasr_dataset.zip and assets.zip

### ISSUE THREAD

**Issue by SofiaLugli** [vasr-dataset/vasr#7]
I've run the `.install.sh` and it successfully downloaded the `images_512.zip`. However, it is unable to download both `vasr_dataset.zip` and `assets.zip`, instead it gives the following errors: 
``` https://my-vasr-bucket.s3.eu-west-1.amazonaws.com/vasr_dataset.zip
Resolving my-vasr-bucket.s3.eu-west-1.amazonaws.com (my-vasr-bucket.s3.eu-west-1.amazonaws.com)... 52.218.30.120, 52.92.35.170, 52.218.122.98, ...
Connecting to my-vasr-bucket.s3.eu-west-1.amazonaws.com (my-vasr-bucket.s3.eu-west-1.amazonaws.com)|52.218.30.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-02 13:37:29 ERROR 404: Not Found.

unzip:  cannot find or open vasr_dataset.zip, vasr_dataset.zip.zip or vasr_dataset.zip.ZIP.
mkdir: cannot create directory ‘experiments/data’: No such file or directory
mv: cannot stat 'vasr_dataset': No such file or directory
--2024-05-02 13:37:29--  https://my-vasr-bucket.s3.eu-west-1.amazonaws.com/assets.zip
Resolving my-vasr-bucket.s3.eu-west-1.amazonaws.com (my-vasr-bucket.s3.eu-west-1.amazonaws.com)... 52.218.30.120, 52.92.35.170, 52.218.122.98, ...
Connecting to my-vasr-bucket.s3.eu-west-1.amazonaws.com (my-vasr-bucket.s3.eu-west-1.amazonaws.com)|52.218.30.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-02 13:37:30 ERROR 404: Not Found.

unzip:  cannot find or open assets.zip, assets.zip.zip or assets.zip.ZIP.
mv: cannot stat 'assets': No such file or directory
mkdir: cannot create directory ‘experiments/data/model_results’: No such file or directory
rm: cannot remove 'vasr_dataset.zip': No such file or directory
rm: cannot remove 'assets.zip': No such file or directory
```
When I open the links for `vasr_dataset.zip` and `assets.zip` using the browser, I got this XML data for both: 
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>my-vasr-bucket</BucketName>
<RequestId>CMDAFH989GZE50X3</RequestId>
<HostId>bt+XaOJK0gDj0ND0GMlQltaWcwSduKB1FgU5In5E5d5L3Mh4G4NbTeXPPqHnOwjTl+2+uFK4cUE=</HostId>
</Error>

```
In https://github.com/vasr-dataset/vasr/tree/main/dataset, the link 
[Download dataset](https://www.google.co.il/) is not properly working as it takes me to a google search page.

**Comment by yonatanbitton** [comment]
Hi, thanks for the interest. You can find downlod links in our website: https://vasr-dataset.github.io/download
For example:
![image](https://github.com/vasr-dataset/vasr/assets/26148975/93482a5a-3f6c-40d7-ab2e-7f2d568f67a2)
Please let me know are there more questions. I'll fix the readme.

**Comment by EurekaZang** [comment]
> Hi, thanks for the interest. You can find downlod links in our website: https://vasr-dataset.github.io/download For example: ![image](https://github.com/vasr-dataset/vasr/assets/26148975/93482a5a-3f6c-40d7-ab2e-7f2d568f67a2) Please let me know are there more questions. I'll fix the readme.

Could you let me know what is in vasr_data.zip? I didnt find vasr_data.zip in your website
